version: 2
updates:
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
  commit-message:
    prefix: "chore"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  commit-message:
    prefix: "chore"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 99
