name: CI

on:
  push:
    branches: [ '**' ]

jobs:
  container_build:
    name: Build and Push Docker Container
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Login to docker hub
      run: docker login --username=chrisjohnson00 --password=${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build the Docker image
      run: |
        docker buildx build --tag chrisjohnson00/qbittorrent-openvpn:${GITHUB_REF##*/} \
          --push --platform  linux/arm/v7,linux/arm64/v8,linux/amd64 .
  actionslint:
    name: 'Actions Yaml Lint'
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Actions Yaml Lint'
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_file_or_dir: '.github/workflows'
          yamllint_comment: true
          yamllint_config_filepath: '.yamllint'
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
