name: Push Latest/Nightly

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # run at 00:00 m-f (which is about 4pm pacific)
    - cron:  '0 0 * * 1-5'

jobs:
  push_latest:
    name: Build and Push Docker Container
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@master
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@master
    - name: Login to docker hub
      run: docker login --username=chrisjohnson00 --password=${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Build the Docker image
      run: |
        docker buildx build --tag chrisjohnson00/qbittorrent-openvpn:latest \
          --push --platform  linux/arm/v7,linux/arm64/v8,linux/amd64 .
